Repository City-of-Helsinki/servicemap-ui, pull requests merged in 2020-10, with the labels that each got.

#499 Prevent dialog showing error message when modalOpen changes to false
  src/views/FeedbackView/FeedbackView.js
Labels: accessibility-independent, bug

#500 Add sentry client side handling
  client/client.js
  config/default.js
  package-lock.json
  package.json
  server/server.js
Labels: accessibility-independent

#502 Improve address and transit stop icon visiblity
  src/views/MapView/components/AddressMarker/AddressMarker.js
  src/views/MapView/components/DistanceMeasure/DistanceMeasure.js
  src/views/MapView/styles.js
Labels: accessibility
